defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "main"

url: "https://developers.keboola.com"

exclude:
  - docker-compose.yml
  - README.md
  - deploy.sh

sass:
  style: compressed

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
